recipe: default.v1
language: en

pipeline:
- name: WhitespaceTokenizer
- name: LanguageModelFeaturizer
  model_name: "distilbert"
  model_weights: "distilbert-base-uncased"
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 20
  use_text_for_featurization: true
  constrain_similarities: true
  tf_gpu_memory_fraction: 0.8
  batch_size: 64
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 20
  constrain_similarities: true
  batch_size: 64
- name: FallbackClassifier
  threshold: 0.7
  ambiguity_threshold: 0.1
- name: RegexEntityExtractor

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 10
  epochs: 20
  similarity_type: 'auto'
  batch_size: 64
- name: TEDPolicy
  max_history: 10
  epochs: 20
  constrain_similarities: true
  batch_size: 64

action_server:
  url: "http://localhost:5055/webhook"

endpoints:
  action_endpoint:
    url: "http://localhost:5055/webhook"
